### ISSUE TITLE
Unloaded tabs don't load when selected with TST 3.4.0

### ISSUE THREAD

**Issue by Argolics** [Lej77/move-unloaded-tabs-for-tree-style-tab#3]
Recent TST release apparently had some internal changes which broke your addon in some subtle ways, i noticed at least the titular issue - i.e. unloaded tabs do not load when selected (they _are_ selected however) from within the TST's tab tree now - before disabling it.
Maybe it's a TST/TST API bug, but at least selecting and loading tabs seem to work in vanilla TST.

FF 73, TST 3.4.1, move unloaded tabs for TST 2.3

**Comment by Lej77** [comment]
This seems like a Tree Style Tab bug. The newest version (v3.4.1) doesn't send the [`tab-mouseup` event](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked) as it should. Anyway this extension isn't really needed on later Tree Style Tab versions since tabs aren't activated/selected by default when they are moved so you should probably just uninstall it.

**Comment by piroor** [comment]
Tracked at https://github.com/piroor/treestyletab/issues/2504 on TST's issue tracker

**Comment by piroor** [comment]
With this commit https://github.com/piroor/treestyletab/commit/f6dcdf9d6594de22f6cd3d6805a85faeb4d9f035 TST sends both tab-mousedown and tab-mouseup even if tab-mousedown is canceled.

**Comment by piroor** [comment]
I've uploaded TST 3.4.4 to AMO with the fix. I'm very sorry that I missed the silent regression over a half of year, and incompatibility from my confusing around DOM event spec...

**Comment by Lej77** [comment]
@piroor Thank you for your tireless work on Tree Style Tab. I really like its addon API that makes it so easy to extend and that you are always quick with fixing any issues!
